### PR TITLE
Added remindme feature

### PR DESCRIPTION
**Pull request by Nanosplitter**
Added dependencies:
```
discord-reply
dateparser
mysql
```

### CODE REVIEW

**Review by bdk99 — COMMENTED** [review]
Add toggle for dev mode to allow developers to easily ignore the sql database and the remindme command.

Put the wait statement as a cron job instead... We don't want wait statements in the middle of the code... That's badd.

**Review by bdk99 — COMMENTED** [review]
Changes comments about command to what the command actually means.  Prints help message doesn't really mean anything since that isn't even what the command does.  I will fix this myself, or you are welcome to fix it as well... But the pull request wont be accepted tonight because I am unable to update the libraries currently running on the bot.

If you have any other questions please feel free to shoot me a message and I will get back to it as soon as I can.

**Comment by Nanosplitter** [comment]
Forgot to update the comment after I copied and edited the one above, fixed now

**Review by bdk99 — COMMENTED** [review]
Add toggle for dev mode to allow developers to easily ignore the sql database and the remindme command.

This is the last thing that needs changed.  Put if statements around both require statements, the command block itself, and the setInterval.

**Comment by Nanosplitter** [comment]
Devs may need a "mysqlurl" var in their config file but they don't need anything in there for the code to still work. Remindme no longer works in devmode

**Review by bdk99 — APPROVED** [review]

**Pull request merged**
